unbind r
bind r source-file ~/.tmux.conf

set -g prefix C-s

# act like vim
setw -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# split panes
bind-key H split-window -h
bind-key V split-window -v

set -s set-clipboard on

# List of plugins
set -g @plugin 'tmux-plugins/tpm'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'


set -g @dracula-show-powerline true
set -g @dracula-fixed-location "Santa Cruz"
set -g @dracula-plugins "weather"
set -g @dracula-show-flags true
set -g @dracula-show-left-icon session
set -g status-position top

# better copy mode
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -in"

# Mimicking the behavior of entering visual mode in Vim, which is familiar to many users who use Vim keybindings.
bind v copy-mode

# C: Using C for "copy" can be intuitive.
bind C copy-mode

# y: Similar to the Vim command for "yank," which is often associated with copying.
bind y copy-mode

bind Enter copy-mode

# scrolling back
set -g history-limit 10000
